---
- hosts: windows
  tasks:
    - name: get disk facts
      win_disk_facts:

    - name: Output first disk size
      debug:
        var: ansible_facts.disk[0].size

    - name: convert first system disk into various formats
      debug:
        msg: '{{ disksize_gib }} vs {{ disksize_gib_human }}'
      vars:
        # get first system disk
        disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'

        #show disk size in gibibytes
        disksize_gib_human: '{{ disk.size|filesizeformat(true) }}'
        disksize_gib: '{{ (disk.size/1024|pow(3))|round|int}} GiB'
