---
- hosts: all
  become: true

  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"

    - name: upate the centos
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: install httpd
      ansible.builtin.yum:
        name: httpd     
        state: present
        
