---
- hosts: localhost
  connection: local

  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "ansible-key"
        instance_type: t3.micro
        security_group: default
        region: ap-south-2
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{ item.name }}"
      loop:
        - { image: "ami-0d3d751381e72e605", name: "managed-1" }
        - { image: "ami-0d3d751381e72e605", name: "managed-2" }
        - { image: "ami-008616ec4a2c6975e", name: "managed-3" }