---
- hosts: windows
  tasks: 
    - name: download the mariadb from link
      win_get_url:
        url: https://mirrors.aliyun.com/mariadb/mariadb-10.10.2/winx64-packages/mariadb-10.10.2-winx64.msi
        dest: C:\Users\demo\Downloads
    - name: install mariadb
      win_package:
        path: C:\Users\demo\Downloads\mariadb-10.10.2-winx64.msi
        product_id: mariadb
        state: present
   


