---
- hosts:192.168.10.46 
  tasks: 
    - name: show system config
      debug:
        msg: "The hostname {{ ansible_hostname }} and os {{ ansible_version }}"
    - name: system info
      debug: var=ansible_facts


